{
e[X1][algorithm(X1)]{a[W][program(W)]{e[][]{a[][]{e[Y,Z][program(Y)]{a[][decides(W,Y,Z)]{e[][False]{}}}; 
e[][]{a[Y,Z][]{e[][]{a[][program(Y),halts2(Y,Z)]{e[][halts3(W,Y,Z),outputs(W,good)]{}}; 
a[][program(Y)]{e[][]{a[][]{e[][halts2(Y,Z)]{}; 
e[][halts3(W,Y,Z),outputs(W,bad)]{}}}}}}}}}}; 
a[][]{e[][]{a[X][]{e[][]{a[][algorithm(X)]{e[][False]{}}}; 
e[Y,Z][program(Y)]{a[][decides(X,Y,Z)]{e[][False]{}}}}}; 
e[W][program(W)]{a[Y][program(Y)]{e[][]{a[Z][]{e[][decides(W,Y,Z)]{}}}}}}; 
a[][]{e[][]{a[W][]{e[][]{a[][program(W)]{e[][False]{}}}; 
e[Y][]{a[][]{e[][program(Y),halts2(Y,Y)]{a[][]{e[][]{a[][halts3(W,Y,Y)]{e[][False]{}}}; 
e[][]{a[][outputs(W,good)]{e[][False]{}}}}}; 
e[][program(Y)]{a[][halts2(Y,Y)]{e[][False]{}}; 
a[][]{e[][]{a[][halts3(W,Y,Y)]{e[][False]{}}}; 
e[][]{a[][outputs(W,bad)]{e[][False]{}}}}}}}}}; 
e[V][program(V)]{a[Y][]{e[][]{a[][program(Y),halts2(Y,Y)]{e[][halts2(V,Y),outputs(V,good)]{}}; 
a[][program(Y)]{e[][]{a[][]{e[][halts2(Y,Y)]{}; 
e[][halts2(V,Y),outputs(V,bad)]{}}}}}}}}; 
a[][]{e[][]{a[V][]{e[][]{a[][program(V)]{e[][False]{}}}; 
e[Y][]{a[][]{e[][program(Y),halts2(Y,Y)]{a[][]{e[][]{a[][halts2(V,Y)]{e[][False]{}}}; 
e[][]{a[][outputs(V,good)]{e[][False]{}}}}}; 
e[][program(Y)]{a[][halts2(Y,Y)]{e[][False]{}}; 
a[][]{e[][]{a[][halts2(V,Y)]{e[][False]{}}}; 
e[][]{a[][outputs(V,bad)]{e[][False]{}}}}}}}}}; 
e[U][program(U)]{a[Y][]{e[][]{a[][program(Y),halts2(Y,Y),halts2(U,Y)]{e[][False]{}}; 
a[][program(Y)]{e[][]{a[][]{e[][halts2(Y,Y)]{}; 
e[][halts2(U,Y),outputs(U,bad)]{}}}}}}}}; 
a[Y1][program(Y1)]{e[][]{a[Z1][]{e[][decides(X1,Y1,Z1)]{}}}}}
}
