{
e[][cUnsatisfiable(i2003_11_14_17_22_10903)]{a[X][]{e[][cowlThing(X)]{a[][cowlNothing(X)]{e[][False]{}}}}; 
a[X][]{e[][]{a[][xsd_string(X),xsd_integer(X)]{e[][False]{}}; 
a[][]{e[][xsd_integer(X)]{}; 
e[][xsd_string(X)]{}}}}; 
a[X][]{e[][]{a[][cUnsatisfiable(X)]{e[Y][rr(X,Y),cowlThing(Y)]{a[Y][rr(X,Y)]{e[][ca_Ax3(Y)]{}}}}; 
a[][]{e[][]{a[Y][]{e[][]{a[][rr(X,Y)]{e[][False]{}}}; 
e[][]{a[][cowlThing(Y)]{e[][False]{}}}}}; 
e[Y][rr(X,Y)]{a[][ca_Ax3(Y)]{e[][False]{}}}; 
e[][cUnsatisfiable(X)]{}}}}; 
a[X][cc(X)]{e[][cdxcomp(X)]{}}; 
a[X][cc1(X)]{e[][cd1(X)]{}}; 
a[X][cc1(X)]{e[][cd1xcomp(X)]{}}; 
a[X][]{e[][]{a[][cd(X)]{e[][[neg(conj([ip_q(e,[Y],t(ra_Px1,[X,Y]))]))]]{}}; 
a[][]{e[Y][ra_Px1(X,Y)]{}; 
e[][cd(X)]{}}}}; 
a[X][]{e[][]{a[][cdxcomp(X)]{e[Y0][ra_Px1(X,Y0)]{}}; 
a[][]{e[][]{a[Y0][ra_Px1(X,Y0)]{e[][False]{}}}; 
e[][cdxcomp(X)]{}}}}; 
a[X][]{e[][]{a[][cd1(X)]{e[Y0][ra_Px2(X,Y0)]{}}; 
a[][]{e[][]{a[Y0][ra_Px2(X,Y0)]{e[][False]{}}}; 
e[][cd1(X)]{}}}}; 
a[X][]{e[][]{a[][cd1xcomp(X)]{e[][[neg(conj([ip_q(e,[Y],t(ra_Px2,[X,Y]))]))]]{}}; 
a[][]{e[Y][ra_Px2(X,Y)]{}; 
e[][cd1xcomp(X)]{}}}}; 
a[X][ce3(X)]{e[][cc(X)]{}}; 
a[X][cf(X)]{e[][cd(X)]{}}; 
a[X][]{e[][]{a[][ca_Ax3(X)]{e[][cd(X),cc(X)]{}}; 
a[][cd(X),cc(X)]{e[][ca_Ax3(X)]{}}}}}
}
