{
e[][]{a[][]{e[U,V][actual_world(U),three(U,V),group(U,V)]{a[X4][]{e[][]{a[][actual_world(X4)]{e[][False]{}}}; 
e[][]{a[X5,X6][]{e[][]{a[][table(X4,X5)]{e[][False]{}}}; 
e[X7][member(X4,X7,X6)]{a[X8][]{e[X9][member(X4,X9,X8)]{a[X10][]{e[][]{a[][event(X4,X10)]{e[][False]{}}}; 
e[][]{a[][agent(X4,X10,X9)]{e[][False]{}}}; 
e[][]{a[][present(X4,X10)]{e[][False]{}}}; 
e[][]{a[][sit(X4,X10)]{e[][False]{}}}; 
e[][]{a[][at(X4,X10,X5)]{e[][False]{}}}; 
e[][]{a[][with(X4,X10,X7)]{e[][False]{}}}}}; 
e[][]{a[][three(X4,X8)]{e[][False]{}}}; 
e[][]{a[][group(X4,X8)]{e[][False]{}}}; 
e[X11][member(X4,X11,X8)]{a[][]{e[][]{a[][guy(X4,X11)]{e[][False]{}}}; 
e[][]{a[][young(X4,X11)]{e[][False]{}}}}}}}; 
e[][]{a[][group(X4,X6)]{e[][False]{}}}; 
e[X12][member(X4,X12,X6)]{a[][hamburger(X4,X12)]{e[][False]{}}}}}}; 
a[W][member(U,W,V)]{e[X,Y][table(U,X),group(U,Y)]{a[Z][member(U,Z,Y)]{e[X1][event(U,X1),agent(U,X1,W),present(U,X1),sit(U,X1),at(U,X1,X),with(U,X1,Z)]{}}; 
a[X2][member(U,X2,Y)]{e[][hamburger(U,X2)]{}}}}; 
a[X3][member(U,X3,V)]{e[][guy(U,X3),young(U,X3)]{}}}; 
e[X4,X5,X6][actual_world(X4),table(X4,X5),group(X4,X6)]{a[U][]{e[][]{a[][actual_world(U)]{e[][False]{}}}; 
e[][]{a[V][]{e[W][member(U,W,V)]{a[X,Y][]{e[][]{a[][table(U,X)]{e[][False]{}}}; 
e[Z][member(U,Z,Y)]{a[X1][]{e[][]{a[][event(U,X1)]{e[][False]{}}}; 
e[][]{a[][agent(U,X1,W)]{e[][False]{}}}; 
e[][]{a[][present(U,X1)]{e[][False]{}}}; 
e[][]{a[][sit(U,X1)]{e[][False]{}}}; 
e[][]{a[][at(U,X1,X)]{e[][False]{}}}; 
e[][]{a[][with(U,X1,Z)]{e[][False]{}}}}}; 
e[][]{a[][group(U,Y)]{e[][False]{}}}; 
e[X2][member(U,X2,Y)]{a[][hamburger(U,X2)]{e[][False]{}}}}}; 
e[][]{a[][three(U,V)]{e[][False]{}}}; 
e[][]{a[][group(U,V)]{e[][False]{}}}; 
e[X3][member(U,X3,V)]{a[][]{e[][]{a[][guy(U,X3)]{e[][False]{}}}; 
e[][]{a[][young(U,X3)]{e[][False]{}}}}}}}}; 
a[X7][member(X4,X7,X6)]{e[X8][three(X4,X8),group(X4,X8)]{a[X9][member(X4,X9,X8)]{e[X10][event(X4,X10),agent(X4,X10,X9),present(X4,X10),sit(X4,X10),at(X4,X10,X5),with(X4,X10,X7)]{}}; 
a[X11][member(X4,X11,X8)]{e[][guy(X4,X11),young(X4,X11)]{}}}}; 
a[X12][member(X4,X12,X6)]{e[][hamburger(X4,X12)]{}}}}}
}
