{
  e[B,C,D,E][subset(B,C),subset(D,E)] {
    a[B,C,D][subset(B,C),subset(C,D)] {
      e[][subset(B,D)] {}};
    a[B,C,D][subset(B,C)] {
      e[][subset(difference(B,D),difference(C,D))] {}};
    a[B,C,D][subset(B,C)] {
      e[][subset(difference(D,C),difference(D,B))] {}};
    a[B,C,D][] {
      e[][] {
        a[][member(D,difference(B,C))] {
          e[][member(D,B)] {
            a[][member(D,C)] {
              e[][False] {}}}};
        a[][member(D,B)] {
          e[][] {
            a[][] {
              e[][member(D,C)] {};
              e[][member(D,difference(B,C))] {}}}}}};
    a[B,C][] {
      e[][] {
        a[][subset(B,C)] {
          e[][] {
            a[D][member(D,B)] {
              e[][member(D,C)] {}}}};
        a[][] {
          e[D][member(D,B)] {
            a[][member(D,C)] {
              e[][False] {}}};
          e[][subset(B,C)] {}}}};
    a[B][] {
      e[][subset(B,B)] {}};
    a[][subset(difference(B,E),difference(C,D))] {
      e[][False] {}}}
}
