{
  e[BNODE_x,BNODE_y,BNODE_l1,BNODE_l2][iext(uri_rdf_type,uri_ex_A,uri_owl_Class),iext(uri_rdf_type,uri_ex_B,uri_owl_Class),iext(uri_rdf_type,uri_ex_w,BNODE_x),iext(uri_owl_intersectionOf,BNODE_x,BNODE_l1),iext(uri_rdf_first,BNODE_l1,uri_ex_A),iext(uri_rdf_rest,BNODE_l1,BNODE_l2),iext(uri_rdf_first,BNODE_l2,BNODE_y),iext(uri_rdf_rest,BNODE_l2,uri_rdf_nil),iext(uri_owl_complementOf,BNODE_y,uri_ex_A)] {
    a[X,C][] {
      e[][] {
        a[][iext(uri_rdf_type,X,C)] {
          e[][icext(C,X)] {}};
        a[][icext(C,X)] {
          e[][iext(uri_rdf_type,X,C)] {}}}};
    a[Z,C][iext(uri_owl_complementOf,Z,C)] {
      e[][ic(Z),ic(C)] {
        a[X][] {
          e[][] {
            a[][icext(Z,X),icext(C,X)] {
              e[][False] {}};
            a[][] {
              e[][icext(C,X)] {};
              e[][icext(Z,X)] {}}}}}};
    a[Z,S1,C1,S2,C2][iext(uri_rdf_first,S1,C1),iext(uri_rdf_rest,S1,S2),iext(uri_rdf_first,S2,C2),iext(uri_rdf_rest,S2,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_intersectionOf,Z,S1)] {
          e[][ic(Z),ic(C1),ic(C2)] {
            a[X][] {
              e[][] {
                a[][icext(Z,X)] {
                  e[][icext(C1,X),icext(C2,X)] {}};
                a[][icext(C1,X),icext(C2,X)] {
                  e[][icext(Z,X)] {}}}}}};
        a[][ic(Z),ic(C1),ic(C2)] {
          e[X][] {
            a[][] {
              e[][icext(Z,X)] {
                a[][] {
                  e[][] {
                    a[][icext(C1,X)] {
                      e[][False] {}}};
                  e[][] {
                    a[][icext(C2,X)] {
                      e[][False] {}}}}};
              e[][icext(C1,X),icext(C2,X)] {
                a[][icext(Z,X)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_intersectionOf,Z,S1)] {}}}};
    a[][iext(uri_rdf_type,uri_ex_w,uri_ex_B)] {
      e[][False] {}}}
}
