{
e[X][big_f(X)]{a[X][big_f(X)]{e[][]{a[][]{e[Y][big_g(Y),big_h(X,Y)]{a[][big_j(X,Y)]{e[][False]{}}}; 
e[][]{a[Y1][]{e[][big_g(Y1),big_h(X,Y1),big_k(Y1)]{}}}}}}; 
a[Y][]{e[][]{a[][big_l(Y)]{e[][False]{}}}; 
e[][]{a[][big_k(Y)]{e[][False]{}}}}; 
a[X][]{e[][]{a[][big_f(X)]{e[][False]{}}}; 
e[Y][big_g(Y),big_h(X,Y)]{}}; 
a[Y][big_h(X,Y)]{e[][big_l(Y)]{}}; 
a[Y1][big_g(Y1),big_h(X,Y1)]{e[][big_j(X,Y1)]{}}}
}
