{
  e[X_grR3,Y_grR3,Z_grR3][convergent_lines(X_grR3,Y_grR3),convergent_lines(Z_grR3,Y_grR3),convergent_lines(X_grR3,Z_grR3),apart_point_and_line(intersection_point(X_grR3,Y_grR3),Z_grR3)] {
    a[X][distinct_points(X,X)] {
      e[][False] {}};
    a[X_7MI3][distinct_lines(X_7MI3,X_7MI3)] {
      e[][False] {}};
    a[X_JGV1][convergent_lines(X_JGV1,X_JGV1)] {
      e[][False] {}};
    a[X_vn93,Y,Z][distinct_points(X_vn93,Y)] {
      e[][] {
        a[][] {
          e[][distinct_points(X_vn93,Z)] {};
          e[][distinct_points(Y,Z)] {}}}};
    a[X_2iM1,Y_2iM1,Z_2iM1][distinct_lines(X_2iM1,Y_2iM1)] {
      e[][] {
        a[][] {
          e[][distinct_lines(X_2iM1,Z_2iM1)] {};
          e[][distinct_lines(Y_2iM1,Z_2iM1)] {}}}};
    a[X_Ncx2,Y_Ncx2,Z_Ncx2][convergent_lines(X_Ncx2,Y_Ncx2)] {
      e[][] {
        a[][] {
          e[][convergent_lines(X_Ncx2,Z_Ncx2)] {};
          e[][convergent_lines(Y_Ncx2,Z_Ncx2)] {}}}};
    a[X_Iy4,Y_Iy4,Z_Iy4][distinct_points(X_Iy4,Y_Iy4)] {
      e[][] {
        a[][apart_point_and_line(Z_Iy4,line_connecting(X_Iy4,Y_Iy4))] {
          e[][distinct_points(Z_Iy4,X_Iy4),distinct_points(Z_Iy4,Y_Iy4),] {}}}};
    a[X_dsX2,Y_dsX2,Z_dsX2][convergent_lines(X_dsX2,Y_dsX2)] {
      e[][] {
        a[][] {
          e[][] {
            a[][apart_point_and_line(Z_dsX2,X_dsX2)] {
              e[][False] {}};
            a[][apart_point_and_line(Z_dsX2,Y_dsX2)] {
              e[][False] {}}};
          e[][distinct_points(Z_dsX2,intersection_point(X_dsX2,Y_dsX2))] {}}}};
    a[X_Y9c,Y_Y9c,U,V][distinct_points(X_Y9c,Y_Y9c),distinct_lines(U,V)] {
      e[][apart_point_and_line(X_Y9c,U)] {};
      e[][apart_point_and_line(X_Y9c,V)] {};
      e[][apart_point_and_line(Y_Y9c,U)] {};
      e[][apart_point_and_line(Y_Y9c,V)] {}};
    a[X_HbT,Y_HbT,Z_HbT][apart_point_and_line(X_HbT,Y_HbT)] {
      e[][] {
        a[][] {
          e[][distinct_points(X_HbT,Z_HbT)] {};
          e[][apart_point_and_line(Z_HbT,Y_HbT)] {}}}};
    a[X_cV21,Y_cV21,Z_cV21][apart_point_and_line(X_cV21,Y_cV21)] {
      e[][] {
        a[][] {
          e[][distinct_lines(Y_cV21,Z_cV21)] {};
          e[][apart_point_and_line(X_cV21,Z_cV21)] {}}}};
    a[X_Xr3,Y_Xr3][convergent_lines(X_Xr3,Y_Xr3)] {
      e[][distinct_lines(X_Xr3,Y_Xr3)] {}};
    a[][apart_point_and_line(intersection_point(Y_grR3,X_grR3),Z_grR3)] {
      e[][False] {}}}
}
