{
  e[][bcapacitysn(n0),qilt27(n0)] {
    a[X][gt(X,X)] {
      e[][False] {}};
    a[X,Y,Z][gt(X,Y),gt(Y,Z)] {
      e[][gt(X,Z)] {}};
    a[X0][] {
      e[][bcapacityne(X0)] {};
      e[][bcapacityex(X0)] {};
      e[][bcapacitysn(X0)] {}};
    a[X0][] {
      e[][] {
        a[][bcapacityne(X0)] {
          e[][False] {}}};
      e[][] {
        a[][bcapacityex(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][] {
        a[][bcapacityne(X0)] {
          e[][False] {}}};
      e[][] {
        a[][bcapacitysn(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][] {
        a[][bcapacityex(X0)] {
          e[][False] {}}};
      e[][] {
        a[][bcapacitysn(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][conditionhyper(X0)] {};
      e[][conditionhypo(X0)] {};
      e[][conditionnormo(X0)] {}};
    a[X0][] {
      e[][] {
        a[][conditionhyper(X0)] {
          e[][False] {}}};
      e[][] {
        a[][conditionhypo(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][] {
        a[][conditionhyper(X0)] {
          e[][False] {}}};
      e[][] {
        a[][conditionnormo(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][] {
        a[][conditionhypo(X0)] {
          e[][False] {}}};
      e[][] {
        a[][conditionnormo(X0)] {
          e[][False] {}}}};
    a[X0][] {
      e[][] {
        a[][] {
          e[X1][] {
            a[][gt(X0,X1)] {
              e[][False] {}};
            a[][drugi(X1)] {
              e[][False] {}}};
          e[][] {
            a[X1][] {
              e[][gt(X0,X1)] {};
              e[][uptakelg(X1),uptakepg(X1)] {
                a[][] {
                  e[][] {}}}}}}}};
    a[X0,X1][] {
      e[][gt(X0,X1)] {};
      e[][] {
        a[][uptakelg(X1),releaselg(X1)] {
          e[][False] {}}}};
    a[X0][] {
      e[X1][] {
        a[][gt(X0,X1)] {
          e[][False] {}};
        a[][drugsu(X1)] {
          e[][False] {}}};
      e[][bcapacityex(X0)] {};
      e[][] {
        a[X1][] {
          e[][gt(X0,X1)] {};
          e[][bsecretioni(X1)] {}}}};
    a[X0][] {
      e[][] {
        a[][] {
          e[X1][] {
            a[][gt(X0,X1)] {
              e[][False] {}};
            a[][drugbg(X1)] {
              e[][False] {}}};
          e[][] {
            a[X1][releaselg(X1)] {
              e[][gt(X0,X1)] {}}}}}};
    a[X0][bcapacitysn(X0),qilt27(X0)] {
      e[X1][] {
        a[][gt(X0,X1)] {
          e[][False] {}};
        a[][bsecretioni(X1)] {
          e[][False] {}}};
      e[X1][gt(X0,X1)] {
        a[][conditionhyper(X1)] {
          e[][False] {}}};
      e[][] {
        a[X1][] {
          e[][gt(X0,X1)] {};
          e[][conditionnormo(X1)] {}}}};
    a[X0][bcapacitysn(X0)] {
      e[X1][releaselg(X1)] {
        a[][gt(X0,X1)] {
          e[][False] {}}};
      e[][qilt27(X0)] {};
      e[X1][gt(X0,X1)] {
        a[][conditionhyper(X1)] {
          e[][False] {}}};
      e[][] {
        a[X1][] {
          e[][gt(X0,X1)] {};
          e[][conditionnormo(X1)] {}}}};
    a[X0][bcapacityne(X0)] {
      e[][] {
        a[][] {
          e[X1][releaselg(X1)] {
            a[][gt(X0,X1)] {
              e[][False] {}}}};
        a[][] {
          e[X1][] {
            a[][gt(X0,X1)] {
              e[][False] {}};
            a[][uptakepg(X1)] {
              e[][False] {}}}}};
      e[X1][] {
        a[][gt(X0,X1)] {
          e[][False] {}};
        a[][bsecretioni(X1)] {
          e[][False] {}}};
      e[X1][gt(X0,X1)] {
        a[][conditionhyper(X1)] {
          e[][False] {}}};
      e[][] {
        a[X1][] {
          e[][gt(X0,X1)] {};
          e[][conditionnormo(X1)] {}}}};
    a[X0][bcapacityex(X0)] {
      e[X1][] {
        a[][gt(X0,X1)] {
          e[][False] {}};
        a[][uptakelg(X1)] {
          e[][False] {}}};
      e[X1][] {
        a[][gt(X0,X1)] {
          e[][False] {}};
        a[][uptakepg(X1)] {
          e[][False] {}}};
      e[X1][gt(X0,X1)] {
        a[][conditionhyper(X1)] {
          e[][False] {}}};
      e[][] {
        a[X1][] {
          e[][gt(X0,X1)] {};
          e[][conditionnormo(X1)] {};
          e[][conditionhypo(X1)] {}}}};
    a[X0][] {
      e[][gt(n0,X0)] {};
      e[][drugsu(X0)] {}};
    a[X0][gt(n0,X0)] {
      e[][conditionhyper(X0)] {}};
    a[][] {
      e[X0][] {
        a[][gt(n0,X0)] {
          e[][False] {}};
        a[][conditionnormo(X0)] {
          e[][False] {}}}}}
}
