{
  e[X_BcT3,BNODE_l1,BNODE_l2,BNODE_l3,BNODE_r][ic(uri_owl_Nothing),ic(uri_owl_Thing),ip(uri_owl_allValuesFrom),ip(uri_owl_complementOf),ip(uri_owl_hasValue),ip(uri_owl_intersectionOf),ip(uri_owl_onProperty),ip(uri_owl_someValuesFrom),ip(uri_owl_unionOf),iext(uri_rdf_type,uri_rdf_first,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_nil,uri_rdf_List),iext(uri_rdf_type,uri_rdf_rest,uri_rdf_Property),iext(uri_rdf_type,uri_rdf__1,uri_rdf_Property),iext(uri_rdf_type,uri_rdf__2,uri_rdf_Property),iext(uri_rdf_type,uri_rdf__3,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_object,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_value,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_subject,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_type,uri_rdf_Property),iext(uri_rdf_type,uri_rdf_type,uri_rdf_Property),iext(uri_rdfs_domain,uri_rdfs_comment,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdfs_comment,uri_rdfs_Literal),iext(uri_rdfs_domain,uri_rdfs_isDefinedBy,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdfs_isDefinedBy,uri_rdfs_Resource),iext(uri_rdfs_subPropertyOf,uri_rdfs_isDefinedBy,uri_rdfs_seeAlso),iext(uri_rdfs_domain,uri_rdfs_label,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdfs_label,uri_rdfs_Literal),iext(uri_rdfs_domain,uri_rdfs_seeAlso,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdfs_seeAlso,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf_first,uri_rdf_List),iext(uri_rdfs_range,uri_rdf_first,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf_rest,uri_rdf_List),iext(uri_rdfs_range,uri_rdf_rest,uri_rdf_List),iext(uri_rdfs_subClassOf,uri_rdf_Alt,uri_rdfs_Container),iext(uri_rdfs_subClassOf,uri_rdf_Bag,uri_rdfs_Container),iext(uri_rdfs_subClassOf,uri_rdfs_ContainerMembershipProperty,uri_rdf_Property),iext(uri_rdfs_domain,uri_rdfs_member,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdfs_member,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf__1,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf__2,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf__3,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdf__1,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdf__2,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdf__3,uri_rdfs_Resource),iext(uri_rdf_type,uri_rdf__1,uri_rdfs_ContainerMembershipProperty),iext(uri_rdf_type,uri_rdf__2,uri_rdfs_ContainerMembershipProperty),iext(uri_rdf_type,uri_rdf__3,uri_rdfs_ContainerMembershipProperty),iext(uri_rdfs_subClassOf,uri_rdfs_Seq,uri_rdfs_Container),iext(uri_rdfs_subClassOf,uri_rdf_XMLLiteral,uri_rdfs_Literal),iext(uri_rdf_type,uri_rdf_XMLLiteral,uri_rdfs_Datatype),iext(uri_rdfs_subClassOf,uri_rdfs_Datatype,uri_rdfs_Class),iext(uri_rdfs_domain,uri_rdfs_domain,uri_rdf_Property),iext(uri_rdfs_range,uri_rdfs_domain,uri_rdfs_Class),iext(uri_rdf_type,uri_rdf_Property,uri_rdfs_Class),iext(uri_rdfs_domain,uri_rdfs_range,uri_rdf_Property),iext(uri_rdfs_range,uri_rdfs_range,uri_rdfs_Class),iext(uri_rdfs_domain,uri_rdf_object,uri_rdfs_Statement),iext(uri_rdfs_range,uri_rdf_predicate,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf_predicate,uri_rdfs_Statement),iext(uri_rdfs_range,uri_rdf_predicate,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdf_subject,uri_rdfs_Statement),iext(uri_rdfs_range,uri_rdf_subject,uri_rdfs_Resource),iext(uri_rdfs_domain,uri_rdfs_subClassOf,uri_rdfs_Class),iext(uri_rdfs_range,uri_rdfs_subClassOf,uri_rdfs_Class),iext(uri_rdfs_domain,uri_rdfs_subPropertyOf,uri_rdf_Property),iext(uri_rdfs_range,uri_rdfs_subPropertyOf,uri_rdf_Property),iext(uri_rdfs_domain,uri_rdf_type,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdf_type,uri_rdfs_Class),iext(uri_rdfs_domain,uri_rdf_value,uri_rdfs_Resource),iext(uri_rdfs_range,uri_rdf_value,uri_rdfs_Resource),ir(X_BcT3),iext(uri_rdf_type,uri_foaf_Person,uri_owl_Class),iext(uri_owl_intersectionOf,uri_ex_PersonAttribute,BNODE_l1),iext(uri_rdf_first,BNODE_l1,uri_owl_DatatypeProperty),iext(uri_rdf_rest,BNODE_l1,BNODE_l2),iext(uri_rdf_first,BNODE_l2,uri_owl_FunctionalProperty),iext(uri_rdf_rest,BNODE_l2,BNODE_l3),iext(uri_rdf_first,BNODE_l3,BNODE_r),iext(uri_rdf_rest,BNODE_l3,uri_rdf_nil),iext(uri_rdf_type,BNODE_r,uri_owl_Restriction),iext(uri_owl_onProperty,BNODE_r,uri_rdfs_domain),iext(uri_owl_hasValue,BNODE_r,uri_foaf_Person),iext(uri_rdf_type,uri_ex_name,uri_ex_PersonAttribute),iext(uri_ex_name,uri_ex_alice,literal_plain(dat_str_alice)),] {
    a[Z,C][iext(uri_owl_complementOf,Z,C)] {
      e[][ic(Z),ic(C)] {
        a[X][] {
          e[][] {
            a[][icext(Z,X),icext(C,X)] {
              e[][False] {}};
            a[][] {
              e[][icext(C,X)] {};
              e[][icext(Z,X)] {}}}}}};
    a[Z_Ncx2][] {
      e[][] {
        a[][iext(uri_owl_intersectionOf,Z_Ncx2,uri_rdf_nil)] {
          e[][ic(Z_Ncx2)] {
            a[X_Iy4][] {
              e[][] {
                a[][icext(Z_Ncx2,X_Iy4)] {
                  e[][ir(X_Iy4)] {}};
                a[][ir(X_Iy4)] {
                  e[][icext(Z_Ncx2,X_Iy4)] {}}}}}};
        a[][ic(Z_Ncx2)] {
          e[X_uQg2][] {
            a[][] {
              e[][icext(Z_Ncx2,X_uQg2)] {
                a[][ir(X_uQg2)] {
                  e[][False] {}}};
              e[][ir(X_uQg2)] {
                a[][icext(Z_Ncx2,X_uQg2)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_intersectionOf,Z_Ncx2,uri_rdf_nil)] {}}}};
    a[Z_Iy4,S1,C1][iext(uri_rdf_first,S1,C1),iext(uri_rdf_rest,S1,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_intersectionOf,Z_Iy4,S1)] {
          e[][ic(Z_Iy4),ic(C1)] {
            a[X_dsX2][] {
              e[][] {
                a[][icext(Z_Iy4,X_dsX2)] {
                  e[][icext(C1,X_dsX2)] {}};
                a[][icext(C1,X_dsX2)] {
                  e[][icext(Z_Iy4,X_dsX2)] {}}}}}};
        a[][ic(Z_Iy4),ic(C1)] {
          e[X_pmk][] {
            a[][] {
              e[][icext(Z_Iy4,X_pmk)] {
                a[][icext(C1,X_pmk)] {
                  e[][False] {}}};
              e[][icext(C1,X_pmk)] {
                a[][icext(Z_Iy4,X_pmk)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_intersectionOf,Z_Iy4,S1)] {}}}};
    a[Z_dsX2,S1_8A12,C1_07x,S2,C2][iext(uri_rdf_first,S1_8A12,C1_07x),iext(uri_rdf_rest,S1_8A12,S2),iext(uri_rdf_first,S2,C2),iext(uri_rdf_rest,S2,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_intersectionOf,Z_dsX2,S1_8A12)] {
          e[][ic(Z_dsX2),ic(C1_07x),ic(C2)] {
            a[X_HbT][] {
              e[][] {
                a[][icext(Z_dsX2,X_HbT)] {
                  e[][icext(C1_07x,X_HbT),icext(C2,X_HbT),] {}};
                a[][icext(C1_07x,X_HbT),icext(C2,X_HbT)] {
                  e[][icext(Z_dsX2,X_HbT)] {}}}}}};
        a[][ic(Z_dsX2),ic(C1_07x),ic(C2)] {
          e[X_t382][] {
            a[][] {
              e[][icext(Z_dsX2,X_t382)] {
                a[][] {
                  e[][] {
                    a[][icext(C1_07x,X_t382)] {
                      e[][False] {}}};
                  e[][] {
                    a[][icext(C2,X_t382)] {
                      e[][False] {}}}}};
              e[][icext(C1_07x,X_t382),icext(C2,X_t382)] {
                a[][icext(Z_dsX2,X_t382)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_intersectionOf,Z_dsX2,S1_8A12)] {}}}};
    a[Z_HbT,S1_Q0K2,C1_I7A1,S2_JW82,C2_BT2,S3,C3][iext(uri_rdf_first,S1_Q0K2,C1_I7A1),iext(uri_rdf_rest,S1_Q0K2,S2_JW82),iext(uri_rdf_first,S2_JW82,C2_BT2),iext(uri_rdf_rest,S2_JW82,S3),iext(uri_rdf_first,S3,C3),iext(uri_rdf_rest,S3,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_intersectionOf,Z_HbT,S1_Q0K2)] {
          e[][ic(Z_HbT),ic(C1_I7A1),ic(C2_BT2),ic(C3)] {
            a[X_4Kn1][] {
              e[][] {
                a[][icext(Z_HbT,X_4Kn1)] {
                  e[][icext(C1_I7A1,X_4Kn1),icext(C2_BT2,X_4Kn1),icext(C3,X_4Kn1),] {}};
                a[][icext(C1_I7A1,X_4Kn1),icext(C2_BT2,X_4Kn1),icext(C3,X_4Kn1)] {
                  e[][icext(Z_HbT,X_4Kn1)] {}}}}}};
        a[][ic(Z_HbT),ic(C1_I7A1),ic(C2_BT2),ic(C3)] {
          e[X_grR3][] {
            a[][] {
              e[][icext(Z_HbT,X_grR3)] {
                a[][] {
                  e[][] {
                    a[][icext(C1_I7A1,X_grR3)] {
                      e[][False] {}}};
                  e[][] {
                    a[][icext(C2_BT2,X_grR3)] {
                      e[][False] {}}};
                  e[][] {
                    a[][icext(C3,X_grR3)] {
                      e[][False] {}}}}};
              e[][icext(C1_I7A1,X_grR3),icext(C2_BT2,X_grR3),icext(C3,X_grR3)] {
                a[][icext(Z_HbT,X_grR3)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_intersectionOf,Z_HbT,S1_Q0K2)] {}}}};
    a[Z_4Kn1][] {
      e[][] {
        a[][iext(uri_owl_unionOf,Z_4Kn1,uri_rdf_nil)] {
          e[][ic(Z_4Kn1)] {
            a[X_PEJ3][icext(Z_4Kn1,X_PEJ3)] {
              e[][False] {}}}};
        a[][ic(Z_4Kn1)] {
          e[X_b8W1][icext(Z_4Kn1,X_b8W1)] {};
          e[][iext(uri_owl_unionOf,Z_4Kn1,uri_rdf_nil)] {}}}};
    a[Z_PEJ3,S1_3lv2,C1_sim1][iext(uri_rdf_first,S1_3lv2,C1_sim1),iext(uri_rdf_rest,S1_3lv2,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_unionOf,Z_PEJ3,S1_3lv2)] {
          e[][ic(Z_PEJ3),ic(C1_sim1)] {
            a[X_37E1][] {
              e[][] {
                a[][icext(Z_PEJ3,X_37E1)] {
                  e[][icext(C1_sim1,X_37E1)] {}};
                a[][icext(C1_sim1,X_37E1)] {
                  e[][icext(Z_PEJ3,X_37E1)] {}}}}}};
        a[][ic(Z_PEJ3),ic(C1_sim1)] {
          e[X_fUy2][] {
            a[][] {
              e[][icext(Z_PEJ3,X_fUy2)] {
                a[][icext(C1_sim1,X_fUy2)] {
                  e[][False] {}}};
              e[][icext(C1_sim1,X_fUy2)] {
                a[][icext(Z_PEJ3,X_fUy2)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_unionOf,Z_PEJ3,S1_3lv2)] {}}}};
    a[Z_37E1,S1_Dc93,C1_5Z02,S2_63_2,C2__2t1][iext(uri_rdf_first,S1_Dc93,C1_5Z02),iext(uri_rdf_rest,S1_Dc93,S2_63_2),iext(uri_rdf_first,S2_63_2,C2__2t1),iext(uri_rdf_rest,S2_63_2,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_unionOf,Z_37E1,S1_Dc93)] {
          e[][ic(Z_37E1),ic(C1_5Z02),ic(C2__2t1)] {
            a[X_vkY2][] {
              e[][] {
                a[][icext(Z_37E1,X_vkY2)] {
                  e[][] {
                    a[][] {
                      e[][icext(C1_5Z02,X_vkY2)] {};
                      e[][icext(C2__2t1,X_vkY2)] {}}}};
                a[][] {
                  e[][] {
                    a[][icext(C1_5Z02,X_vkY2)] {
                      e[][False] {}};
                    a[][icext(C2__2t1,X_vkY2)] {
                      e[][False] {}}};
                  e[][icext(Z_37E1,X_vkY2)] {}}}}}};
        a[][ic(Z_37E1),ic(C1_5Z02),ic(C2__2t1)] {
          e[X_2fl][] {
            a[][] {
              e[][icext(Z_37E1,X_2fl)] {
                a[][icext(C1_5Z02,X_2fl)] {
                  e[][False] {}};
                a[][icext(C2__2t1,X_2fl)] {
                  e[][False] {}}};
              e[][] {
                a[][] {
                  e[][icext(C1_5Z02,X_2fl)] {};
                  e[][icext(C2__2t1,X_2fl)] {}};
                a[][icext(Z_37E1,X_2fl)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_unionOf,Z_37E1,S1_Dc93)] {}}}};
    a[Z_vkY2,S1_asT1,C1_SpK,S2_TJI1,C2_LG9,S3_Mp61,C3_eKU3][iext(uri_rdf_first,S1_asT1,C1_SpK),iext(uri_rdf_rest,S1_asT1,S2_TJI1),iext(uri_rdf_first,S2_TJI1,C2_LG9),iext(uri_rdf_rest,S2_TJI1,S3_Mp61),iext(uri_rdf_first,S3_Mp61,C3_eKU3),iext(uri_rdf_rest,S3_Mp61,uri_rdf_nil)] {
      e[][] {
        a[][iext(uri_owl_unionOf,Z_vkY2,S1_asT1)] {
          e[][ic(Z_vkY2),ic(C1_SpK),ic(C2_LG9),ic(C3_eKU3)] {
            a[X_1ID][] {
              e[][] {
                a[][icext(Z_vkY2,X_1ID)] {
                  e[][] {
                    a[][] {
                      e[][icext(C1_SpK,X_1ID)] {};
                      e[][icext(C2_LG9,X_1ID)] {};
                      e[][icext(C3_eKU3,X_1ID)] {}}}};
                a[][] {
                  e[][] {
                    a[][icext(C1_SpK,X_1ID)] {
                      e[][False] {}};
                    a[][icext(C2_LG9,X_1ID)] {
                      e[][False] {}};
                    a[][icext(C3_eKU3,X_1ID)] {
                      e[][False] {}}};
                  e[][icext(Z_vkY2,X_1ID)] {}}}}}};
        a[][ic(Z_vkY2),ic(C1_SpK),ic(C2_LG9),ic(C3_eKU3)] {
          e[X_dpw1][] {
            a[][] {
              e[][icext(Z_vkY2,X_dpw1)] {
                a[][icext(C1_SpK,X_dpw1)] {
                  e[][False] {}};
                a[][icext(C2_LG9,X_dpw1)] {
                  e[][False] {}};
                a[][icext(C3_eKU3,X_dpw1)] {
                  e[][False] {}}};
              e[][] {
                a[][] {
                  e[][icext(C1_SpK,X_dpw1)] {};
                  e[][icext(C2_LG9,X_dpw1)] {};
                  e[][icext(C3_eKU3,X_dpw1)] {}};
                a[][icext(Z_vkY2,X_dpw1)] {
                  e[][False] {}}}}};
          e[][iext(uri_owl_unionOf,Z_vkY2,S1_asT1)] {}}}};
    a[X_pj4][icext(uri_owl_Nothing,X_pj4)] {
      e[][False] {}};
    a[X_MCo1][] {
      e[][] {
        a[][icext(uri_owl_Thing,X_MCo1)] {
          e[][ir(X_MCo1)] {}};
        a[][ir(X_MCo1)] {
          e[][icext(uri_owl_Thing,X_MCo1)] {}}}};
    a[X_yjS3][ic(X_yjS3)] {
      e[][] {
        a[Y][icext(X_yjS3,Y)] {
          e[][ir(Y)] {}}}};
    a[X_5ef1][ic(X_5ef1)] {
      e[][ir(X_5ef1)] {}};
    a[X_h6K3][] {
      e[][] {
        a[][ic(X_h6K3)] {
          e[][iext(uri_rdf_type,X_h6K3,uri_rdfs_Class)] {}};
        a[][iext(uri_rdf_type,X_h6K3,uri_rdfs_Class)] {
          e[][ic(X_h6K3)] {}}}};
    a[X_t0X1][idc(X_t0X1)] {
      e[][] {
        a[Y_t0X1][icext(X_t0X1,Y_t0X1)] {
          e[][lv(Y_t0X1)] {}}}};
    a[X_cSO1][idc(X_cSO1)] {
      e[][ic(X_cSO1)] {}};
    a[X_9323][] {
      e[][] {
        a[][idc(X_9323)] {
          e[][iext(uri_rdf_type,X_9323,uri_rdfs_Datatype)] {}};
        a[][iext(uri_rdf_type,X_9323,uri_rdfs_Datatype)] {
          e[][idc(X_9323)] {}}}};
    a[X_LuF1][ioap(X_LuF1)] {
      e[][] {
        a[Y_LuF1,Z_LuF1][iext(X_LuF1,Y_LuF1,Z_LuF1)] {
          e[][ir(Y_LuF1),ir(Z_LuF1),] {}}}};
    a[X_goq2][ioap(X_goq2)] {
      e[][ip(X_goq2)] {}};
    a[X_si_][] {
      e[][] {
        a[][ioap(X_si_)] {
          e[][iext(uri_rdf_type,X_si_,uri_owl_AnnotationProperty)] {}};
        a[][iext(uri_rdf_type,X_si_,uri_owl_AnnotationProperty)] {
          e[][ioap(X_si_)] {}}}};
    a[X_PBi2][iodp(X_PBi2)] {
      e[][] {
        a[Y_PBi2,Z_PBi2][iext(X_PBi2,Y_PBi2,Z_PBi2)] {
          e[][ir(Y_PBi2),lv(Z_PBi2),] {}}}};
    a[X_KXm][iodp(X_KXm)] {
      e[][ip(X_KXm)] {}};
    a[X_w2Q2][] {
      e[][] {
        a[][iodp(X_w2Q2)] {
          e[][iext(uri_rdf_type,X_w2Q2,uri_owl_DatatypeProperty)] {}};
        a[][iext(uri_rdf_type,X_w2Q2,uri_owl_DatatypeProperty)] {
          e[][iodp(X_w2Q2)] {}}}};
    a[X_3zd][ioxp(X_3zd)] {
      e[][] {
        a[Y_3zd,Z_3zd][iext(X_3zd,Y_3zd,Z_3zd)] {
          e[][ix(Y_3zd),ix(Z_3zd),] {}}}};
    a[X_Ot92][ioxp(X_Ot92)] {
      e[][ip(X_Ot92)] {}};
    a[X_anM][] {
      e[][] {
        a[][ioxp(X_anM)] {
          e[][iext(uri_rdf_type,X_anM,uri_owl_OntologyProperty)] {}};
        a[][iext(uri_rdf_type,X_anM,uri_owl_OntologyProperty)] {
          e[][ioxp(X_anM)] {}}}};
    a[X_7G12][ip(X_7G12)] {
      e[][] {
        a[Y_7G12,Z_7G12][iext(X_7G12,Y_7G12,Z_7G12)] {
          e[][ir(Y_7G12),ir(Z_7G12),] {}}}};
    a[X_2c5][ip(X_2c5)] {
      e[][ir(X_2c5)] {}};
    a[X_e4p1][] {
      e[][] {
        a[][ip(X_e4p1)] {
          e[][iext(uri_rdf_type,X_e4p1,uri_rdf_Property)] {}};
        a[][iext(uri_rdf_type,X_e4p1,uri_rdf_Property)] {
          e[][ip(X_e4p1)] {}}}};
    a[X_NWg1][] {
      e[][] {
        a[][ir(X_NWg1)] {
          e[][iext(uri_rdf_type,X_NWg1,uri_rdfs_Resource)] {}};
        a[][iext(uri_rdf_type,X_NWg1,uri_rdfs_Resource)] {
          e[][ir(X_NWg1)] {}}}};
    a[X_z_K3][ix(X_z_K3)] {
      e[][ir(X_z_K3)] {}};
    a[X_6yX1][] {
      e[][] {
        a[][ix(X_6yX1)] {
          e[][iext(uri_rdf_type,X_6yX1,uri_owl_Ontology)] {}};
        a[][iext(uri_rdf_type,X_6yX1,uri_owl_Ontology)] {
          e[][ix(X_6yX1)] {}}}};
    a[X_iQC3][lv(X_iQC3)] {
      e[][ir(X_iQC3)] {}};
    a[X_uKP1][] {
      e[][] {
        a[][lv(X_uKP1)] {
          e[][iext(uri_rdf_type,X_uKP1,uri_rdfs_Literal)] {}};
        a[][iext(uri_rdf_type,X_uKP1,uri_rdfs_Literal)] {
          e[][lv(X_uKP1)] {}}}};
    a[X_Rs33,Y_Rs33][iext(uri_owl_allValuesFrom,X_Rs33,Y_Rs33)] {
      e[][icext(uri_owl_Restriction,X_Rs33),ic(Y_Rs33),] {}};
    a[X_AF32,Y_AF32][iext(uri_owl_complementOf,X_AF32,Y_AF32)] {
      e[][ic(X_AF32),ic(Y_AF32),] {}};
    a[X_ygr2,Y_ygr2][iext(uri_owl_hasValue,X_ygr2,Y_ygr2)] {
      e[][icext(uri_owl_Restriction,X_ygr2),ir(Y_ygr2),] {}};
    a[X_h3j2,Y_h3j2][iext(uri_owl_intersectionOf,X_h3j2,Y_h3j2)] {
      e[][ic(X_h3j2),icext(uri_rdf_List,Y_h3j2),] {}};
    a[X_QVa2,Y_QVa2][iext(uri_owl_onProperty,X_QVa2,Y_QVa2)] {
      e[][icext(uri_owl_Restriction,X_QVa2),ip(Y_QVa2),] {}};
    a[X_9xR2,Y_9xR2][iext(uri_owl_someValuesFrom,X_9xR2,Y_9xR2)] {
      e[][icext(uri_owl_Restriction,X_9xR2),ic(Y_9xR2),] {}};
    a[X_xJJ2,Y_xJJ2][iext(uri_owl_unionOf,X_xJJ2,Y_xJJ2)] {
      e[][ic(X_xJJ2),icext(uri_rdf_List,Y_xJJ2),] {}};
    a[P,C_iNb2][] {
      e[][] {
        a[][iext(uri_rdfs_domain,P,C_iNb2)] {
          e[][ip(P),ic(C_iNb2)] {
            a[X_sfN,Y_sfN][iext(P,X_sfN,Y_sfN)] {
              e[][icext(C_iNb2,X_sfN)] {}}}};
        a[][ip(P),ic(C_iNb2)] {
          e[X_b2F,Y_b2F][iext(P,X_b2F,Y_b2F)] {
            a[][icext(C_iNb2,X_b2F)] {
              e[][False] {}}};
          e[][iext(uri_rdfs_domain,P,C_iNb2)] {}}}};
    a[P_jk43,C_ydB2][] {
      e[][] {
        a[][iext(uri_rdfs_range,P_jk43,C_ydB2)] {
          e[][ip(P_jk43),ip(C_ydB2)] {
            a[X_TUU3,Y_TUU3][iext(P_jk43,X_TUU3,Y_TUU3)] {
              e[][icext(C_ydB2,Y_TUU3)] {}}}};
        a[][ip(P_jk43),ip(C_ydB2)] {
          e[X_CwL3,Y_CwL3][iext(P_jk43,X_CwL3,Y_CwL3)] {
            a[][icext(C_ydB2,Y_CwL3)] {
              e[][False] {}}};
          e[][iext(uri_rdfs_range,P_jk43,C_ydB2)] {}}}};
    a[C1_2H21,C2_AH41][] {
      e[][] {
        a[][iext(uri_rdfs_subClassOf,C1_2H21,C2_AH41)] {
          e[][ic(C1_2H21),ic(C2_AH41)] {
            a[X_jk43][icext(C1_2H21,X_jk43)] {
              e[][icext(C2_AH41,X_jk43)] {}}}};
        a[][ic(C1_2H21),ic(C2_AH41)] {
          e[X_veH1][icext(C1_2H21,X_veH1)] {
            a[][icext(C2_AH41,X_veH1)] {
              e[][False] {}}};
          e[][iext(uri_rdfs_subClassOf,C1_2H21,C2_AH41)] {}}}};
    a[P1,P2][] {
      e[][] {
        a[][iext(uri_rdfs_subPropertyOf,P1,P2)] {
          e[][ip(P1),ip(P2)] {
            a[X_S742,Y_S742][iext(P1,X_S742,Y_S742)] {
              e[][iext(P2,X_S742,Y_S742)] {}}}};
        a[][ip(P1),ip(P2)] {
          e[X_BZs2,Y_BZs2][iext(P1,X_BZs2,Y_BZs2)] {
            a[][iext(P2,X_BZs2,Y_BZs2)] {
              e[][False] {}}};
          e[][iext(uri_rdfs_subPropertyOf,P1,P2)] {}}}};
    a[Z_BZs2,P_5YO,C_k242][iext(uri_owl_allValuesFrom,Z_BZs2,C_k242),iext(uri_owl_onProperty,Z_BZs2,P_5YO)] {
      e[][] {
        a[X_uHo][] {
          e[][] {
            a[][icext(Z_BZs2,X_uHo)] {
              e[][] {
                a[Y_uHo][iext(P_5YO,X_uHo,Y_uHo)] {
                  e[][icext(C_k242,Y_uHo)] {}}}};
            a[][] {
              e[Y_RpS2][iext(P_5YO,X_uHo,Y_RpS2)] {
                a[][icext(C_k242,Y_RpS2)] {
                  e[][False] {}}};
              e[][icext(Z_BZs2,X_uHo)] {}}}}}};
    a[Z_RpS2,P_lMV3,A][iext(uri_owl_hasValue,Z_RpS2,A),iext(uri_owl_onProperty,Z_RpS2,P_lMV3)] {
      e[][] {
        a[X_ydB2][] {
          e[][] {
            a[][icext(Z_RpS2,X_ydB2)] {
              e[][iext(P_lMV3,X_ydB2,A)] {}};
            a[][iext(P_lMV3,X_ydB2,A)] {
              e[][icext(Z_RpS2,X_ydB2)] {}}}}}};
    a[Z_M6X,P_giZ1,C_vbg][iext(uri_owl_someValuesFrom,Z_M6X,C_vbg),iext(uri_owl_onProperty,Z_M6X,P_giZ1)] {
      e[][] {
        a[X_QSz1][] {
          e[][] {
            a[][icext(Z_M6X,X_QSz1)] {
              e[Y_QSz1][iext(P_giZ1,X_QSz1,Y_QSz1),icext(C_vbg,Y_QSz1),] {}};
            a[][] {
              e[][] {
                a[Y_cM7][] {
                  e[][] {
                    a[][iext(P_giZ1,X_QSz1,Y_cM7)] {
                      e[][False] {}}};
                  e[][] {
                    a[][icext(C_vbg,Y_cM7)] {
                      e[][False] {}}}}};
              e[][icext(Z_M6X,X_QSz1)] {}}}}}};
    a[P_k242][] {
      e[][] {
        a[][iext(uri_rdf_type,P_k242,uri_rdf_Property)] {
          e[][ip(P_k242)] {}};
        a[][ip(P_k242)] {
          e[][iext(uri_rdf_type,P_k242,uri_rdf_Property)] {}}}};
    a[X_xGi1,C_6sG][] {
      e[][] {
        a[][iext(uri_rdf_type,X_xGi1,C_6sG)] {
          e[][icext(C_6sG,X_xGi1)] {}};
        a[][icext(C_6sG,X_xGi1)] {
          e[][iext(uri_rdf_type,X_xGi1,C_6sG)] {}}}};
    a[C_iK31][ic(C_iK31)] {
      e[][iext(uri_rdfs_subClassOf,C_iK31,uri_rdfs_Resource)] {}};
    a[P_Ctk2][icext(uri_rdfs_ContainerMembershipProperty,P_Ctk2)] {
      e[][iext(uri_rdfs_subPropertyOf,P_Ctk2,uri_rdfs_member)] {}};
    a[D][icext(uri_rdfs_Datatype,D)] {
      e[][iext(uri_rdfs_subClassOf,D,uri_rdfs_Literal)] {}};
    a[P_Onx,C__EW3,X_8XI1,Y_8XI1][iext(uri_rdfs_domain,P_Onx,C__EW3),iext(P_Onx,X_8XI1,Y_8XI1)] {
      e[][icext(C__EW3,X_8XI1)] {}};
    a[X_wy91][] {
      e[][] {
        a[][ic(X_wy91)] {
          e[][icext(uri_rdfs_Class,X_wy91)] {}};
        a[][icext(uri_rdfs_Class,X_wy91)] {
          e[][ic(X_wy91)] {}}}};
    a[X_TRt2][] {
      e[][] {
        a[][ir(X_TRt2)] {
          e[][icext(uri_rdfs_Resource,X_TRt2)] {}};
        a[][icext(uri_rdfs_Resource,X_TRt2)] {
          e[][ir(X_TRt2)] {}}}};
    a[X_fL11][] {
      e[][] {
        a[][lv(X_fL11)] {
          e[][icext(uri_rdfs_Literal,X_fL11)] {}};
        a[][icext(uri_rdfs_Literal,X_fL11)] {
          e[][lv(X_fL11)] {}}}};
    a[P_BWC2,C_QPJ1,X_3Fc2,Y_3Fc2][iext(uri_rdfs_range,P_BWC2,C_QPJ1),iext(P_BWC2,X_3Fc2,Y_3Fc2)] {
      e[][icext(C_QPJ1,Y_3Fc2)] {}};
    a[C_lJu2,D_lJu2][iext(uri_rdfs_subClassOf,C_lJu2,D_lJu2)] {
      e[][ic(C_lJu2),ic(D_lJu2)] {
        a[X_S4L2][icext(C_lJu2,X_S4L2)] {
          e[][icext(D_lJu2,X_S4L2)] {}}}};
    a[C_gfy][ic(C_gfy)] {
      e[][iext(uri_rdfs_subClassOf,C_gfy,C_gfy)] {}};
    a[C_D8d2,D_D8d2,E][iext(uri_rdfs_subClassOf,C_D8d2,D_D8d2),iext(uri_rdfs_subClassOf,D_D8d2,E)] {
      e[][iext(uri_rdfs_subClassOf,C_D8d2,E)] {}};
    a[P_yaa1,Q][iext(uri_rdfs_subPropertyOf,P_yaa1,Q)] {
      e[][ip(P_yaa1),ip(Q)] {
        a[X_6sG,Y_6sG][iext(P_yaa1,X_6sG,Y_6sG)] {
          e[][iext(Q,X_6sG,Y_6sG)] {}}}};
    a[P_EV63][ip(P_EV63)] {
      e[][iext(uri_rdfs_subPropertyOf,P_EV63,P_EV63)] {}};
    a[P_QPJ1,Q_QPJ1,R][iext(uri_rdfs_subPropertyOf,P_QPJ1,Q_QPJ1),iext(uri_rdfs_subPropertyOf,Q_QPJ1,R)] {
      e[][iext(uri_rdfs_subPropertyOf,P_QPJ1,R)] {}};
    a[S,P_9rA1,O][iext(P_9rA1,S,O)] {
      e[][ip(P_9rA1)] {}};
    a[X_mgN3][] {
      e[][ir(X_mgN3)] {}};
    a[X_yaa1][lv(X_yaa1)] {
      e[][ir(X_yaa1)] {}};
    a[][] {
      e[][] {
        a[][iext(uri_rdf_type,uri_ex_name,uri_owl_FunctionalProperty)] {
          e[][False] {}}};
      e[][] {
        a[][iext(uri_rdf_type,uri_ex_alice,uri_foaf_Person)] {
          e[][False] {}}}}}
}
